### ISSUE TITLE
ManifoldParameter is not working

### ISSUE THREAD

**Issue by Agathon-geo** [geoopt/geoopt#104]
Hi @ferrine ,

following my discussion with @LeanderK  in https://github.com/geoopt/geoopt/issues/97
`ManifoldParameter()` returns error : 
```
stiefel = geoopt.manifolds.Stiefel()
X = geoopt.ManifoldParameter(torch.randn(20, 10), manifold=stiefel)
```
I ge the following error :

```
geoopt/tensor.py", line 146, in __new__
    instance.manifold = data.manifold
AttributeError: can't set attribute
```

Thank you

**Comment by ferrine** [comment]
Looks like changes on pytorch side broke some geoopt code. I will fix that as soon as possible

**Comment by Agathon-geo** [comment]
Yes @ferrine, thank you for fixing that

**Comment by ferrine** [comment]
@Agathon-geo could you please provide the way you installed Geoopt? I'm particularly interested in pytorch installation/version since I was not able to reproduce the error locally.

**Comment by Agathon-geo** [comment]
```

Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda custom (64-bit) on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
'8.0.44'
>>> torch.__version__
'1.1.0'
>>> import geoopt
>>> geoopt.__version__
'0.0.1'
```
l installed Geoopt  as you mentionned :
`pip install git+https://github.com/geoopt/geoopt.git`
and pytorch : 
`conda install pytorch=1.1.0 cuda80 -c pytorch`

**Comment by Agathon-geo** [comment]
@ferrine , l think the problem comes from  pytorch version 1.1.0 which is not stable or cuda8 , l just tried pytorch 1.2.0 with cuda10 and it worked

**Comment by ferrine** [comment]
Can we close the issue?

**Comment by Agathon-geo** [comment]
Yes @ferrine , for sure. Thank you
