### ISSUE TITLE
Gyrovector spaces (Poincare ball & Stereographic projection)

### ISSUE THREAD

**Issue by emilemathieu** [geoopt/geoopt#110]
Hi all,
First, thanks a lot for this great package, it is insanely convenient!

Two recent papers ([Mixed-curvature Variational Autoencoders](https://openreview.net/forum?id=S1g6xeSKDS) and [Constant Curvature Graph Convolutional Networks](https://openreview.net/forum?id=BJg73xHtvr)) frame the Poincare ball and stereographic projection of the hypersphere under the gyrovector space framework.

I was wondering whether there was any plan of implementing the stereographic projection of the hypersphere? If not I may be able to take some time to do at some point. Also, I know one of the author so will ask about sharing the code.

cheers
emile

**Comment by emilemathieu** [comment]
On a tangential note, some may be interested by the hyperboloid (also called Lorentz) model. If so, I have an implementation that I could share.

**Comment by rrkarim** [comment]
@emilemathieu we have some plans of implementing Lorentz model. But you are very welcome to open PR by yourself.

**Comment by ferrine** [comment]
We already have Stereographic projection, closing
