### ISSUE TITLE
Regression to points in Poincarè Disk Model 

### ISSUE THREAD

**Issue by NooneBug** [geoopt/geoopt#120]
Hi,

I'm building neural network in pytorch which has to learn to make regression from vectors in Euclidean Space to some vectors in Poincarè Disk Model, so I think that the usage of RiemannianSGD can be a good choice as the optimizer.

I'm trying to use the library but I have some question:

- When and how I have to cast tensors? 
Now I transform the target tensors with ManifoldTensor with `Y = ManifoldTensor(Y, manifold = geoopt.manifolds.PoincareBall()`, I think that even the prediction has to be a Manifold Tensor, but if I transform the prediction outside the model the `ManifoldTensor ` does not maintain the `grad` value

- Have I to build each layer of the network with `ManifoldTensor` or `torch.nn.Linear` can be used?
- Have I to specify to the optimizer `RiemannianSGD` the manifold? From the documentation I think that I don't have to do it

Anyway thanks for your work on this project ; - )

**Comment by ferrine** [comment]
Hi. Generally, no need to cast every tensor to manifold tensor (I tried to implement that, but thhere were more drawbacks). Manifold tensor is a data structure used in R-Optimizers. 

You can look at examples folder for Mobius Linear to get intuition how to build layers on poicare ball. Additionally, you can use arbitrary nonlinear functions in the tangent space with ball.mobius_apply_fn.

**Comment by NooneBug** [comment]
Ok, so if I understand if have to use a `MobiusLinear` for each linear layer that I want to put in the network and the `RiemannianSGD` (or the `RiemannianAdam`) applied to that network will work as expected.

In your opinion, I have to use only `MobiusLinear` or I can use `Linear` for first layers and `MobiusLinear` for the last layers?

Thanks a lot

**Comment by ferrine** [comment]
I usually apply some Euclidean layers to Euclidean input and then do exponential map onto Poincare ball. There are some more complicated ways to map between spaces like averaging centroids but this would require some extra code.

in-74-128-D-exp-mob_linear... architecture may work not bad

**Comment by ferrine** [comment]
Be careful with nonlinearity in Poincare ball. Pointwise nonlinearity is quite ambiguous

**Comment by NooneBug** [comment]
If I don't use `MobiusLinear` the `RiemannianAdam` will not work as intended?

**Comment by ferrine** [comment]
It will. It is required in case you have manifold valued parameters. For regular parameter it is same as Adam

**Comment by ferrine** [comment]
Should I close the issue?

**Comment by ISaidNoOneBug** [comment]
Yes, I solved this problem thanks go you and it seems that it works very well.

Thanks a lot
