### ISSUE TITLE
Error on import geoopt

### ISSUE THREAD

**Issue by NooneBug** [geoopt/geoopt#128]
Hi, 

I recently updated the pytorch environment library and so I installed again geoopt via : `pip install git+https://github.com/geoopt/geoopt.git`

When I try to import the library this is the error that is reported to me:
```

  import geoopt
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/geoopt/__init__.py", line 1, in <module>
    from . import manifolds
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/geoopt/manifolds/__init__.py", line 3, in <module>
    from .stiefel import Stiefel, EuclideanStiefel, CanonicalStiefel, EuclideanStiefelExact
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/geoopt/manifolds/stiefel.py", line 4, in <module>
    from .. import linalg
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/geoopt/linalg/__init__.py", line 1, in <module>
    from .batch_linalg import svd, qr, sym, extract_diag, matrix_rank, expm, block_matrix
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/geoopt/linalg/batch_linalg.py", line 3, in <module>
    from . import _expm
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/geoopt/linalg/_expm.py", line 8, in <module>
    @torch.jit.script
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/torch/jit/__init__.py", line 364, in script
    graph = _script_graph(fn, _frames_up=_frames_up + 1)
  File "/home/vmanuel/.conda/envs/MTNCI/lib/python3.6/site-packages/torch/jit/__init__.py", line 360, in _script_graph
    return _jit_script_compile(ast, rcb)
RuntimeError: 
builtin cannot be used as a value:
        33522128640.0,
        1323241920.0,
        40840800.0,
        960960.0,
        16380.0,
        182.0,
        1.0,
    )

    ident = torch.eye(A.shape[1], dtype=A.dtype, device=A.device)
                      ~~~~~~~ <--- HERE
    A2 = torch.matmul(A, A)
    A4 = torch.matmul(A2, A2)
    A6 = torch.matmul(A4, A2)
    U = torch.matmul(
        A,
        torch.matmul(A6, b13 * A6 + b11 * A4 + b9 * A2)
        + b7 * A6
        + b5 * A4
        + b3 * A2
```

Can you help me?

**Comment by ferrine** [comment]
Hi, can you please provide your pytorch version?

**Comment by NooneBug** [comment]
Hi, I'm making some test and I accidentally modified the environment on which I found the problem, but I noticed that the problem can be between the package`allennlp` which install pytorch 0.4, I think that torch and pytorch have the same signature .

I'm trying to make clean tests:

- Create an env, 
- install geoopt with `pip install git+https://github.com/geoopt/geoopt.git`, 
- try `import geoopt` (this works)

- Create an env, 
- install geoopt with `pip install git+https://github.com/geoopt/geoopt.git`,
- `conda install -c conda-forge allennlp`
- `import geoopt` (in progress)

- Create an env,
- `conda install -c conda-forge allennlp`,
- install geoopt with `pip install git+https://github.com/geoopt/geoopt.git`,
- `import geoopt` (in progress)

I'll report here the results of these tests asap, if you have some hints I'll be glad to know them ; )

**Comment by NooneBug** [comment]
Test 3 generates this: 
![Screenshot from 2020-03-17 14-04-02](https://user-images.githubusercontent.com/22955986/76858713-4e66eb80-6858-11ea-83fd-882639f9d1b0.png)

But as you can see, even with the error the import works...
I think is solved, but I'm a little confused from this behaviour...

**Comment by ferrine** [comment]
So as I see, `allennlp` installs a lower version of pytorch and this causes the problem. Old pytorch does not have much jit support.

**Comment by ferrine** [comment]
Does allennlp work with latest pytorch?

**Comment by NooneBug** [comment]
Yes, before this morning I didn't noticed any error in AllenNLP usage, I think that my previous setup was exactly the test 3.

**Comment by ferrine** [comment]
ok. so let's close the issue
