### ISSUE TITLE
why `exp_avg_sq ` updated with point * grad not grad * grad

### ISSUE THREAD

**Issue by jianing-sun** [geoopt/geoopt#146]
Hello, 

Thanks for the code. I have a question: why in `radam.py` for updating `exp_avg_sq` you have `manifold.component_inner(point, grad)`. Shouldn't it be something like `inner(grad, grad)`? based on the Adam algorithm (also in Figure 1 (a) in your paper).

Also, what it `component inner` mean? What's it used for?  Can't I just do `grad * grad`?

Thanks!

Jianing

**Comment by jianing-sun** [comment]
I figured that the first parameter here `point` is just for taking the shape not actually for any inner product operation. The real operation of that function is still grad * grad. 

But my other question remains: what's the difference of `component_inner` against `inner`? Is there any special operation in it that we should be aware of?

**Comment by ferrine** [comment]
Component inner is here to take in account product spaces where adaptive
term can be per component. The method itself is required for
ProductManifold: some inners collapse dimensions, some not, but we need to
concat them

**Comment by jianing-sun** [comment]
I see. So it's specific for product spaces with adaptive term. For spaces without that, like lorentz or poincare model, we can just do `inner` on the gradient. 

Thanks for your response!
