### ISSUE TITLE
Current use of add_ is deprecated

### ISSUE THREAD

**Issue by AlexanderZeilmann** [geoopt/geoopt#148]
The way [```add_```](https://pytorch.org/docs/stable/tensors.html?highlight=add_#torch.Tensor.add_) is used in several places in geoopt is deprecated, yielding the following warning:

> /usr/local/lib/anaconda3/lib/python3.7/site-packages/geoopt/optim/rsgd.py:96: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  grad.add_(weight_decay, point)

[```Version 1.4.0```](https://pytorch.org/docs/1.4.0/tensors.html?highlight=add_#torch.Tensor.add_) had the API

    add_(value=1, other) -> Tensor

[```Version 1.5.0```](https://pytorch.org/docs/1.5.0/tensors.html?highlight=add_#torch.Tensor.add_) has the API

    add_(other, *, alpha=1) → Tensor

This means for example line [96 in rsgd.py](https://github.com/geoopt/geoopt/blob/master/geoopt/optim/rsgd.py#L96)

    grad.add_(weight_decay, point)

should be

    grad.add_(point, *, alpha = weight_decay)

So far I did not check whether this only applies to ```add_``` or if there are other similar functions.

**Comment by ferrine** [comment]
Thanks, I'm planning a maintenance update and will fix that deprecation as well
