### ISSUE TITLE
What's the function of setup.py and how can i use it?

### ISSUE THREAD

**Issue by CallMeNumber1** [geoopt/geoopt#152]

**Comment by newkozlukov** [comment]
It allows you to build a "wheel" (a reusable distribution, akin to java's `jar`) and/or install it into your environment, e.g.:

- `pip install git+https://github.com/geoopt/geoopt.git`
- https://github.com/geoopt/geoopt/blob/b92a3c8a4870fc60a902b4c81daf64f682f2cef9/.github/workflows/pythonpublish.yml#L25

You may want to acquaint with
- https://packaging.python.org/tutorials/packaging-projects/
- and more modern https://github.com/python-poetry/poetry/
- and https://github.com/takluyver/flit
