### ISSUE TITLE
 No module named 'geoopt.manifolds.poincare'

### ISSUE THREAD

**Issue by Apollo201** [geoopt/geoopt#156]
Hi,

When I try to `import geoopt.manifolds.poincare.math as pmath?`

it told me that: `No module named 'geoopt.manifolds.poincare'`

How to solve it?
Thanks very much

**Comment by AlexanderZeilmann** [comment]
There is no manifold called ```poincare```. 

You probably want 
```
from geoopt import PoincareBall
```

**Comment by Apollo201** [comment]
Thanks for reply, the import sentence is found from here: https://geoopt.readthedocs.io/en/poincare/plots/extended/poincare/mobius_add.py, line1

Thanks
@AlexanderZeilmann

**Comment by sounritesh** [comment]
@Apollo201 did you find the solution to this issue?
I am facing the same issue

Thanks

**Comment by ferrine** [comment]
https://geoopt.readthedocs.io/en/poincare points to an old branch, use https://geoopt.readthedocs.io/en/latest
