### ISSUE TITLE
Question on Distance2PoincareHyperplanes

### ISSUE THREAD

**Issue by molbap** [geoopt/geoopt#169]
In the example notebook hyperbolic_multiclass_classification, the layer Distance2PoincareHyperplanes defines the distance in the forward pass as 

```
distance = self.ball.dist2plane(
            x=input_p, p=points, a=points, signed=self.signed, dim=-self.n - 2
        )
```

Where points are defined as

```

        self.points = geoopt.ManifoldParameter(
            torch.empty(num_planes, plane_shape), manifold=self.ball
        )
        points = self.points.permute(1, 0)
        points = points.view(points.shape + (1,) * self.n)

```

My question is, **why are the parameters a and p equal?** In the dist2plane definition, a belongs to the tangent space of the manifold, and p is a point on the manifold itself. It is not obvious to me why these two entries should be equal.

**Comment by ferrine** [comment]
The idea was to remove overparametrization. You can any plane with a single parameter
