### ISSUE TITLE
Pytorch 1.12 is not compatible with geoopt 0.5.0

### ISSUE THREAD

**Issue by ferrine** [geoopt/geoopt#196]
Need to upgrade the codebase for pytorch 1.12

**Comment by amiltonwong** [comment]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 import geoopt

File ~/anaconda3/envs/duo-fm/lib/python3.8/site-packages/geoopt/__init__.py:1, in <module>
----> 1 from . import manifolds
      2 from . import optim
      3 from . import tensor

File ~/anaconda3/envs/duo-fm/lib/python3.8/site-packages/geoopt/manifolds/__init__.py:13, in <module>
     11 from .symmetric_positive_definite import SymmetricPositiveDefinite
     12 from .siegel import UpperHalf, BoundedDomain
---> 13 from .stereographic import (
     14     PoincareBall,
     15     PoincareBallExact,
     16     Stereographic,
     17     StereographicExact,
     18     SphereProjection,
     19     SphereProjectionExact,
     20 )
     21 from .product import ProductManifold, StereographicProductManifold
     22 from .lorentz import Lorentz

File ~/anaconda3/envs/duo-fm/lib/python3.8/site-packages/geoopt/manifolds/stereographic/__init__.py:1, in <module>
----> 1 from .manifold import (
      2     Stereographic,
      3     StereographicExact,
      4     PoincareBall,
      5     PoincareBallExact,
      6     SphereProjection,
      7     SphereProjectionExact,
      8 )
     10 from . import math

File ~/anaconda3/envs/duo-fm/lib/python3.8/site-packages/geoopt/manifolds/stereographic/manifold.py:3, in <module>
      1 import torch.nn
      2 from typing import Tuple, Optional, List
----> 3 from . import math
      4 import geoopt
      5 from ...utils import size2shape, broadcast_shapes

File ~/anaconda3/envs/duo-fm/lib/python3.8/site-packages/geoopt/manifolds/stereographic/math.py:1231, in <module>
   1197     r"""
   1198     Compute the generalization of matrix-vector multiplication in gyrovector spaces.
   1199 
   (...)
   1225         Möbius matvec result
   1226     """
   1227     return _mobius_matvec(m, x, k, dim=dim)
   1230 @torch.jit.script
-> 1231 def _mobius_matvec(m: torch.Tensor, x: torch.Tensor, k: torch.Tensor, dim: int = -1):
   1232     if m.dim() > 2 and dim != -1:
   1233         raise RuntimeError(
   1234             "broadcasted Möbius matvec is supported for the last dim only"
   1235         )

File ~/anaconda3/envs/duo-fm/lib/python3.8/site-packages/torch/jit/_script.py:989, in script(obj, optimize, _frames_up, _rcb)
    985 memo[obj_id] = obj
    987 new_obj_dict = {}
--> 989 for name, sub_module in obj.__dict__.items():
    990     if name == '_modules':
    991         for k, v in sub_module.items():

RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::tensordot(Tensor self, Tensor other, int[] dims_self, int[] dims_other) -> (Tensor):
  Expected a value of type 'List[int]' for argument 'dims_self' but instead found type 'Tuple[List[int], List[int]]'.
  
  aten::tensordot.out(Tensor self, Tensor other, int[] dims_self, int[] dims_other, *, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'List[int]' for argument 'dims_self' but instead found type 'Tuple[List[int], List[int]]'.

The original call is:
  File "/root/anaconda3/envs/duo-fm/lib/python3.8/site-packages/geoopt/manifolds/stereographic/math.py", line 1238
    x_norm = x.norm(dim=dim, keepdim=True, p=2).clamp_min(1e-15)
    if dim != -1 or m.dim() == 2:
        mx = torch.tensordot(x, m, ([dim], [1]))
             ~~~~~~~~~~~~~~~ <--- HERE
    else:
        mx = torch.matmul(m, x.unsqueeze(-1)).squeeze(-1)

**Comment by amiltonwong** [comment]
I've tried installing geoopt (0.5.0) together with pytorch 1.12, and got the error above when import geoopt

**Comment by ferrine** [comment]
it is updated that this specific version is marked incompatible
