### ISSUE TITLE
Docs are failing

### ISSUE THREAD

**Issue by ferrine** [geoopt/geoopt#206]
Read The Docs installs some default dependencies that require GPU. A proper setup is required
https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by SauravMaheshkar** [comment]
Can you provide some more context @ferrine

**Comment by ferrine** [comment]
I went back to this issue, seems to be configuration only. Originally, it was due to pytorch convolved build 1.12, later on it was out of the radar.

**Comment by ferrine** [comment]
RTD seems to still fetch gpu version of pytorch, but the build seems to go fine
