### ISSUE TITLE
Unneeded regexps for autowiring retractions

### ISSUE THREAD

**Issue by newkozlukov** [geoopt/geoopt#46]
Current implementation of `ManifoldMeta` uses regular expressions to determine
functions implementing retractions and stuff. While this reduces the amount of client code (the client here being an implementation of specific manifold) by some single line, this 1) makes things less explicit (one needs to check out `ManifoldMeta` docs/sources to make sure `_retr1` really does what it does and the way it does it; 2) makes things more complex

Using e.g. a decorator would allow for better explicitness and possibly simpler `ManifoldMeta` implementation

**Comment by newkozlukov** [comment]
A sketch of possible solution: https://github.com/newkozlukov/geoopt/blob/ManifoldMeta_decorators/geoopt/manifolds/base.py

**Comment by ferrine** [comment]
Closed via #77
