### ISSUE TITLE
Embedded manifold viewpoint

### ISSUE THREAD

**Issue by newkozlukov** [geoopt/geoopt#53]
Current `Manifold`'s API presumes Manifold is embedded into \mathbb{R}^d
and includes methods like `egrad2rgrad`, etc. It also seems that a single global chart is -- though I'm not sure -- implicitly assumed, which would make the very use of the word "Manifold" a little exaggerative

**Comment by ferrine** [comment]
Yes, docstrings indeed assume that. However, we can implement manifolds that are not embedded in R^n, e.g. distributions. But this will require some refactoring. The key thing is how do we perform steps in Manifold and how do we treap parameters. Parameters are now just tensors but could be arbitrary objects.

**Comment by newkozlukov** [comment]
Embededness is partially justified by immersion theorems, in the sense that both intrinsic and extrinsic definitions [describe same class of manifolds](https://terrytao.wordpress.com/2016/05/11/notes-on-the-nash-embedding-theorem/). However it still seems possible to me to encounter even in applications manifolds that aren't _conveniently_ described by embeddings. After all, as one of the uses of this geometric framework it is supposed that it'll provide _natural_ coordinates

(I still need that course on diff geometry...)

**Comment by ferrine** [comment]
We need to redesign an API. I agree with that. We should start with designing an architecture. I want us to be constructive and make several assumptions. I like the design of https://github.com/geomstats/geomstats that does not make a lot of assumptions on Manifold structure. 

I have concerns about manifolds that do not have ambient spaces. From my point of view, if we do not assume and embedded space, we would get stuck with implementation design without having a motivating example to check that works efficiently or properly. So at this particular development stage, I would assume that we have ambient space and leave your idea for big future ambitious PR.

**Comment by ferrine** [comment]
Can I close the issue? It seems to be dead as well. BTW I was asked to create some place where we can freely discuss differential geometry and related things. We can move these discussions there. But need to decide about the place.

**Comment by newkozlukov** [comment]
Yeah, it got stale and I our perception of this problem must've changed a lot since these discussions. We better restart with clear context
