### ISSUE TITLE
setup.py: `version_file` relative path

### ISSUE THREAD

**Issue by newkozlukov** [geoopt/geoopt#55]
0. Clone project
1. Change to whatever folder except `geoopt` tree root
2. Run `python $GEOOPT/setup.py develop` or `install`

Observe:
```
FileNotFoundError: [Errno 2] No such file or directory: 'geoopt/__init__.py'
```

Solution: extract absolute path to the running script, then concatenate with `'geoopt/__init__.py'`

Also, extracting a variable from `__init__.py` via regexp feels a little smelly.

**Comment by ferrine** [comment]
While fixing this, I noticed that installation goes wrong if `setup` file is called within another directory. Searching SO I found a related issue https://stackoverflow.com/questions/53871285/calling-python-setup-py-install-from-another-directory
Where one guy says that it is a non supposed way to do that. My initial attempts to solve this problem failed. I'd prefer to fix relative path issue and not to support any location setup file runner. pip installation from any location works totally fine
