### ISSUE TITLE
$c$ counter-inuitively stands for **negative** curvature

### ISSUE THREAD

**Issue by newkozlukov** [geoopt/geoopt#59]
Currently the `c` parameter in `PoincareBall` defines **negative** curvature
though it is most natural to assume `c` to be just curvature.
That is unconventional, misleading, and is likely to cause inconsistencies some time later

**Comment by newkozlukov** [comment]
Could call radius, in case of Poincare ball

**Comment by ferrine** [comment]
This would be inverse square radius

--
Max

вт, 19 мар. 2019 г., 17:47 Sergei Kozlukov <notifications@github.com>:

**Comment by newkozlukov** [comment]
> This would be inverse square radius

Umm, yeah, sorry

**Comment by ferrine** [comment]
I personally think c is the least ugly

**Comment by newkozlukov** [comment]
I personally think `c` is the ugliest thing possible. I'd even rather `nc` (as in neg. curvature) than confusing the reader in such a way. But the correct approach, I believe, would be to change methods to accept the actual curvature, and not what's basically its absolute value

**Comment by ferrine** [comment]
I am fine with changing parametrization to radius. We can follow Lee or Ungar notation, `r` and `c` respectively

**Comment by newkozlukov** [comment]
Let's stick with Lee, perhaps?

**Comment by ferrine** [comment]
I had issues when refactoring with new parametrization. you can find my attempts here:  https://github.com/geoopt/geoopt/tree/parametrization

**Comment by newkozlukov** [comment]
Perhaps just refer to it as to the speed of light

**Comment by newkozlukov** [comment]
@ferrine numerical issues caused by renaming a variable?

**Comment by ferrine** [comment]
No, parametrization

пн, 22 апр. 2019 г., 13:42 Sergei Kozlukov <notifications@github.com>:

**Comment by ferrine** [comment]
Btw, c is not the speed of light

пн, 22 апр. 2019 г., 15:28 Maxim Kochurov <maxim.v.kochurov@gmail.com>:

**Comment by newkozlukov** [comment]
> Btw, c is not the speed of light 

In the only model that we more or less have an idea how to derive (that is one of relativistic velocities with Einstein addition) it is. As for `c` in Mobius addition -- it was apparently named so by an analogy, and it is still the radius of the ball of "admissible" vectors, so... "speed of light" seems to be the only title that makes at least some sense

**Comment by ferrine** [comment]
The ball radius is 1/c**.5

пн, 22 апр. 2019 г., 17:50 Sergei Kozlukov <notifications@github.com>:

**Comment by newkozlukov** [comment]
> The ball radius is 1/c**.5


Ah... That's easily forgotten, I fell out of the context. I'll try not to rant about all that being inconsistent with Ungar (even though I'm not a big fan of how his works are written), with interpretation, and with authors of HNN paper initially talking about the ball of radius `c` (right before they produce that same incosistency)

**Comment by ferrine** [comment]
Can I close the issue?

**Comment by ferrine** [comment]
Closed due to incativity
