### ISSUE TITLE
Gaining more visibility

### ISSUE THREAD

**Issue by calincru** [geoopt/geoopt#83]
You might consider letting the people who work on [manopt](https://www.manopt.org) know about this project and having you listed under [Related Software](https://www.manopt.org/about.html) (they have a "Let us know!" hyperlink there).

I think this is more promising than other Python variants of (or similar to) manopt because of the tight integration with PyTorch.  The multi-backend approach of pymanopt, for instance, sounds good at first but it ultimately leads to unnecessary maintenance hell on the devs' side and missing features on the user side.

I'm personally working on adding support for some new manifolds.  Will send you PRs once they seem to be working as expected

**Comment by ferrine** [comment]
Hi! 
Thank you for your interest! We actually did not think about notifying them, but it sounds like a great idea to gain more visibility and attract the community.

Upcoming contributions sound really encouraging, looking forward to this.

Pytorch adds some mental pain with the design, e.g. you can see #81. We are looking for workarounds on dev side to make UX better, but did not come up with a consensus solution. Major tasks and milestones are listed in here https://github.com/geoopt/geoopt/projects

**Comment by calincru** [comment]
Will take a look and let you know what else I find out while developing. :+1:
