### ISSUE TITLE
Do we really want to support `*more` in functions?

### ISSUE THREAD

**Issue by ferrine** [geoopt/geoopt#89]
This is still unused feature ([here](https://github.com/geoopt/geoopt/blob/master/geoopt/manifolds/base.py#L336)) in our experience so we might consider just delete it in favor of cleaner api and developer friendliness. Personally, I now see no reason to maintain it.

CC @calincru

**Comment by calincru** [comment]
I sent https://github.com/geoopt/geoopt/pull/91.

**Comment by ferrine** [comment]
Finished
