### ISSUE TITLE
How to properly use ManifoldParameter

### ISSUE THREAD

**Issue by LeanderK** [geoopt/geoopt#97]
I currently use the following piece of code:

```python
if self.init_id:
    init = torch.eye(input_dims[0]).view((input_dims[0], input_dims[0], 1, 1))
else:
    init = torch.randn(input_dims[0], input_dims[0])# + input_dims[0]*torch.eye(input_dims[0])
self.orth_w = geoopt.ManifoldParameter(init, manifold=stiefel_man)
```
but if init is random, it won't be on the stiefel-manifold! So i tried `self.orth_w.proj_()`, but it tells me: 

RuntimeError: a leaf Variable that requires grad has been used in an in-place operation.

I can guard the `.proj_()` with a `with torch.no_grad()`, but I don't know whether this is the right approach.

I just want to do a straightforward matrix-multiplication on the forward pass and want `geoopt` to not leave the stiefel-manifold during my training.

**Comment by ferrine** [comment]
Yes, you are right, you need the context manager in order to remove this error. This happens to stay consistent with torch inplace operations behavior.

You may also like `Stiefel.random_naive` method. It will return manifold tensor on the manifold you can wrap in `ManifoldParameter`.

**Comment by ferrine** [comment]
Make sure manifold dimensions are the last ones, it seems to be wrong in init_id if branch

**Comment by LeanderK** [comment]
ok, yeah just noticed it also. I don't use init_id=True for some time. 
Thanks!

**Comment by Agathon-geo** [comment]
Hi @ferrine  & @LeanderK 
ManifoldParameter is not working for me, l get error at geoopt/tensor.py"
Here is what l have tried : 

```

import torch
import geoopt #Riemannian Adaptive Optimization Methods with pytorch optim

class My_ConvNet(nn.Module):

    def __init__(self, net_parameters):
        super(My_ConvNet, self).__init__()
        
        
        x_dim_stiefel, y_dim_stiefel,features_dim,dim_output = net_parameters# x_dim_stiefel=10, y_dim_stiefel=5
        #Stiefel Manifold
        stiefel_man = geoopt.Stiefel()

        self.Stiefel = geoopt.ManifoldTensor(torch.randn(x_dim_stiefel, y_dim_stiefel), 	manifold=stiefel_man, required_grad=True).cuda()
	#Euclidean Manifold
	eucl_man = geoopt.Euclidean()
	self.Euclidian =    geoopt.ManifoldTensor(torch.randn(y_dim_stiefel, 	 	x_dim_stiefel), manifold= 		eucl_man, 			  required_grad=True).cuda()

	# fully connected layer (standard pytorch layer based on nn.torch

	self.fc1 = nn.Linear(features_dim, dim_output)



    def forward(self,x):
        
        Te = self.Stiefel.mm(self.Euclidian)
        x=torch.mm(Te,x)
	x=self.fc1(x)
	x=torch.nn.functional.softmax(x)
        return x


net_parameters=[x_dim_stiefel, y_dim_stiefel,features_dim,dim_output]
net=My_ConvNet(net_parameters)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), learning_rate,
                                momentum=0.9,
                                weight_decay=0.0001)
```

The fact that l used `ManifoldTensor()` rather than` ManifoldParameter()` no backward on `self.Stiefel`, `self.Euclidian` and on   `x=torch.mm(Te,x)` (weights are kept unchanged) but it supposed to backward.


Then, l tried the following by replacing  `ManifoldTensor()` by `ManifoldParameter()` as follow : 

```
import torch
import geoopt #Riemannian Adaptive Optimization Methods with pytorch optim

class My_ConvNet(nn.Module):

    def __init__(self, net_parameters):
        super(My_ConvNet, self).__init__()
        
        
        x_dim_stiefel, y_dim_stiefel,features_dim,dim_output = net_parameters# x_dim_stiefel=10, y_dim_stiefel=5
        #Stiefel Manifold
        stiefel_man = geoopt.Stiefel()

        self.Stiefel = geoopt.ManifoldParameter(torch.randn(x_dim_stiefel,y_dim_stiefel), manifold=stiefel_man)
	#Euclidean Manifold
	eucl_man = geoopt.Euclidean()
	self.Euclidian = geoopt.ManifoldParameter(torch.randn(y_dim_stiefel,x_dim_stiefel), manifold=eucl_man)

	# fully connected layer (standard pytorch layer based on nn.torch

	self.fc1 = torch.nn.Linear(features_dim, dim_output)



    def forward(self,x):
        
        Te = self.Stiefel.mm(self.Euclidian)
        x=torch.mm(Te,x)
	x=self.fc1(x)
	x=torch.nn.functional.softmax(x)
        return x


net_parameters=[x_dim_stiefel, y_dim_stiefel,features_dim,dim_output]
net=My_ConvNet(net_parameters)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), learning_rate,
                                momentum=0.9,
                                weight_decay=0.0001)
```

I get the following error  : 
```
geoopt/tensor.py", line 146, in __new__
    instance.manifold = data.manifold
AttributeError: can't set attribute
```

After 
 `       self.Stiefel = geoopt.ManifoldParameter(torch.randn(x_dim_stiefel,y_dim_stiefel), manifold=stiefel_man)`

and after 

`self.Euclidian = geoopt.ManifoldParameter(torch.randn(y_dim_stiefel,x_dim_stiefel), manifold=eucl_man)
`

**Comment by LeanderK** [comment]
On my phone, but I think you're using the wrong optimizer (`torch.optim.SGD`). Only geoopts optimizer can optimize inside non-euclidian manifolds? (At least it's crucial in practice, you need to stabilize the stiefel manifold).

**Comment by Agathon-geo** [comment]
Thank you @LeanderK  for your response :  
1)Before diving into the choice of optimizer, even the following line of code is not working
`stiefel_man = geoopt.Stiefel()`
l get the following error :  
```
geoopt/tensor.py", line 146, in __new__
    instance.manifold = data.manifold
AttributeError: can't set attribute
```
after this line of code : 
`Stiefel = geoopt.ManifoldParameter(torch.randn(36,8), manifold=stiefel_man)`

2)You are right for `torch.optim.SGD` l have to use instead :  `geoopt.optim.RiemannianSGD`, but does the latter optimizes` self.fc1 = torch.nn.Linear(features_dim, dim_output)` ? 
Thank you

**Comment by LeanderK** [comment]
to 1), are you using code comparable to this? Because your error doesn't make sense.

```python
stiefel = geoopt.manifolds.Stiefel()
X = geoopt.ManifoldParameter(torch.randn(20, 10), manifold=stiefel)
```
(note that you should call these lines after initializing you paramter:
```python
with torch.no_grad():
   X.proj_()
```
)
2) geoopt.optim.RiemannianSGD optmizises a superset of torch.optim.SGD

**Comment by LeanderK** [comment]
if the code is similiar to my answer is not working you should create a new issue

**Comment by Agathon-geo** [comment]
Yes, the following is not working : 
```
stiefel = geoopt.manifolds.Stiefel()
X = geoopt.ManifoldParameter(torch.randn(20, 10), manifold=stiefel)
```
I ge the following error : 
```
geoopt/tensor.py", line 146, in __new__
    instance.manifold = data.manifold
AttributeError: can't set attribute
```
l create a new issue

**Comment by Agathon-geo** [comment]
New issue is created here https://github.com/geoopt/geoopt/issues/104

**Comment by Agathon-geo** [comment]
> to 1), are you using code comparable to this? Because your error doesn't make sense.
> 
> ```python
> stiefel = geoopt.manifolds.Stiefel()
> X = geoopt.ManifoldParameter(torch.randn(20, 10), manifold=stiefel)
> ```
> 
> (note that you should call these lines after initializing you paramter:
> 
> ```python
> with torch.no_grad():
>    X.proj_()
> ```
Why you put `torch.no_grad():` ? l need to backpropagte on it !
> 
> )
> 2) geoopt.optim.RiemannianSGD optmizises a superset of torch.optim.SGD

**Comment by LeanderK** [comment]
> with torch.no_grad():
>    X.proj_()
> Why you put torch.no_grad(): ? l need to backpropagte on it !
this is only an inplace operation to initialize the thing. There are no gradients flowing yet.
